name: embedded_db_benchmark
repository: https://github.com/blaugold/embedded_db_benchmark
packages:
  - packages/**
  - '*'

ide:
  intellij: false

scripts:
  format: dart format .
  format:check: dart format --set-exit-if-changed .
  analyze:
    run: melos exec -c 1 -- dart analyze --fatal-infos
  code_gen:build_runner:
    run: melos exec -c 1 -- dart pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope:
        - drift_provider
        - hive_provider
        - isar_provider
        - objectbox_provider
  code_gen:realm:
    run: melos exec -c 1 -- dart pub run realm_dart generate
    packageFilters:
      scope:
        - realm_provider
