name: hive_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  hive: ^2.2.1

dev_dependencies:
  build_runner: any
  hive_generator: ^1.1.3
