name: drift_document
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  benchmark_document:
    path: ../benchmark_document
  drift: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.8
  drift_dev: ^1.5.2
  flutter_lints: ^1.0.4
