name: runner_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  cbl: ^1.0.3
  cbl_flutter: ^1.0.0+2
  cbl_flutter_ce: ^1.0.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  isar_flutter_libs: ^2.2.1
  logging: ^1.0.2
  objectbox_flutter_libs: ^1.4.1
  realm: ^0.2.0+alpha

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/benchmark/src/fixture/documents.json
