name: runner_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  cbl: ^2.1.0
  cbl_flutter: ^2.0.1
  cbl_flutter_ce: ^2.1.1
  cbl_provider:
    path: ../cbl_provider
  cupertino_icons: ^1.0.5
  drift_provider:
    path: ../drift_provider
  flutter:
    sdk: flutter
  hive_provider:
    path: ../hive_provider
  isar_flutter_libs: ^2.5.0
  isar_provider:
    path: ../isar_provider
  logging: ^1.0.2
  objectbox_flutter_libs: ^1.6.0
  objectbox_provider:
    path: ../objectbox_provider
  path_provider: ^2.0.11
  realm: 0.4.0+beta
  realm_provider:
    path: ../realm_provider
  sqlite3_flutter_libs: ^0.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/benchmark/src/fixture/documents.json
