name: isar_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  isar: ^2.2.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  isar_generator: ^2.2.1
