name: isar_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  isar: ^3.0.0-dev.14

dev_dependencies:
  build_runner: any
  isar_generator: ^3.0.0-dev.14
