name: objectbox_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  objectbox: ^2.0.0

dev_dependencies:
  build_runner: any
  objectbox_generator: ^2.0.0
