name: objectbox_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  objectbox: ^1.7.2

dev_dependencies:
  build_runner: any
  objectbox_generator: 1.7.2
