name: objectbox_document
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  benchmark_document:
    path: ../benchmark_document
  objectbox: ^1.4.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  objectbox_generator: 1.4.1
