name: objectbox_document
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  objectbox: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.4
  objectbox_generator: any
