name: benchmark
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  benchmark_harness: ^2.0.0
  cbl: ^1.0.0
  cbl_dart: ^1.0.0
  hive: ^2.0.5
  isar: ^2.2.0+1
  isar_document:
    path: ../isar_document
  objectbox: ^1.3.0
  objectbox_document:
    path: ../objectbox_document
  realm_dart: ^0.2.0+alpha
  realm_document:
    path: ../realm_document

dev_dependencies:
  flutter_lints: ^1.0.4
