name: benchmark
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  csv: ^5.0.1
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.0
  tabular: ^0.6.3+1
  test: ^1.19.0

dev_dependencies:
  flutter_lints: ^1.0.4
