name: benchmark
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  beto_client: ^0.1.0
  beto_common: ^0.1.0
  collection: ^1.16.0
  csv: ^5.0.2
  logging: ^1.1.1
  meta: ^1.8.0
  path: ^1.8.2
  stats: ^2.0.0
  tabular: ^0.6.3+1
  test: ^1.21.1
