name: runner_dart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  cbl: ^1.0.2
  cbl_dart: ^1.0.0+2
  logging: ^1.0.2
  path: ^1.8.1
  realm_dart: ^0.2.0+alpha

dev_dependencies:
  flutter_lints: ^1.0.4
