name: hive_document
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  hive: ^2.0.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
