name: cbl_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  cbl: ^1.0.5
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.4
