name: drift_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  drift: ^2.0.2+1
  http: ^0.13.5
  path: ^1.8.0
  sqlite3: ^1.8.0

dev_dependencies:
  build_runner: any
  drift_dev: ^2.0.2
