name: drift_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  drift: ^1.6.0
  path: ^1.8.0

dev_dependencies:
  build_runner: any
  drift_dev: ^1.6.0
