name: drift_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  drift: ^1.7.0
  http: ^0.13.4
  path: ^1.8.0
  sqlite3: ^1.7.2

dev_dependencies:
  build_runner: any
  drift_dev: ^1.7.0
