name: cli
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.0
  benchmark:
    path: ../benchmark
  cbl: ^2.1.8
  cbl_dart: ^2.1.9
  cbl_provider:
    path: ../cbl_provider
  drift_provider:
    path: ../drift_provider
  hive_provider:
    path: ../hive_provider
  isar_provider:
    path: ../isar_provider
  logging: ^1.1.1
  objectbox_provider:
    path: ../objectbox_provider
  path: ^1.8.2
  realm_dart: 1.0.2
  realm_provider:
    path: ../realm_provider
