name: realm_provider
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  benchmark:
    path: ../benchmark
  realm_dart: ^0.2.0+alpha

dev_dependencies:
  flutter_lints: ^1.0.4
