name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Check format
        run: melos run format:check

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Bootstrap packages
        run: melos bs
      - name: Analyze
        run: melos run analyze

  run-benchmark-dart:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compilation: [jit, aot]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Bootstrap package
        run: melos bs --scope runner_dart
      - name: Install Realm binaries
        working-directory: packages/runner_dart
        run: dart run realm_dart install
      - name: Install Objectbox binaries
        working-directory: packages/runner_dart
        shell: bash
        run:
          eval "$(curl -s
          https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)"
      - name: Run benchmark (JIT)
        if: ${{ matrix.compilation == 'jit' }}
        working-directory: packages/runner_dart
        run: dart run
      - name: Run benchmark (AOT)
        if: ${{ matrix.compilation == 'aot' }}
        shell: bash
        working-directory: packages/runner_dart
        run: bin/runner_dart_aot.sh

  run-benchmark-flutter:
    # For some reason when running the benchmark in Flutter there are random crashes.
    # For now we don't count these as failures.
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Flutter dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run:
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
          liblzma-dev
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Enable Flutter platforms
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Ensure Flutter generated files exist
        working-directory: packages/runner_flutter
        run: flutter pub get
      - name: Bootstrap package
        run: melos bs --scope runner_flutter
      - name: Run benchmark
        working-directory: packages/runner_flutter
        shell: bash
        run: |
          case ${{ runner.os }} in
            Linux)
              device=linux
              ;;
            macOS)
              device=macos
              ;;
            Windows)
              device=windows
              ;;
          esac
          flutter test -v -d $device integration_test/benchmark_test.dart
