name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Check format
        run: melos run format:check

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Bootstrap packages
        run: melos bs
      - name: Analyze
        run: melos run analyze

  run-benchmark-dart:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Bootstrap packages
        run: melos bs --scope runner_dart
      - name: Install Realm binaries
        working-directory: packages/runner_dart
        run: dart run realm_dart install
      - name: Install Objectbox binaries
        working-directory: packages/runner_dart
        shell: bash
        run: eval "$(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)"
      - name: Run benchmark
        working-directory: packages/runner_dart
        run: dart run
