name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  deploy-web-app:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Deploy app
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: packages/app
          baseHref: /embedded_db_benchmark/
